In [ ]:
1. Write the Python code to implement a single neuron.


In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

class Neuron:
    def __init__(self, input_size):
        self.weights = np.random.randn(input_size)
        self.bias = np.random.randn()

    def forward(self, inputs):
        total = np.dot(inputs, self.weights) + self.bias
        output = sigmoid(total)
        return output

# Example usage
input_data = np.array([0.5, 0.3, 0.2])
neuron = Neuron(input_size=3)
output = neuron.forward(input_data)
print(output)


0.5016238187244485


In [ ]:
2. Write the Python code to implement ReLU.


In [2]:
import numpy as np

def relu(x):
    return np.maximum(0, x)

# Example usage
input_data = np.array([-1, 2, -3, 4])
output = relu(input_data)
print(output)


[0 2 0 4]


In [ ]:
3. Write the Python code for a dense layer in terms of matrix multiplication.


In [3]:
import numpy as np

class DenseLayer:
    def __init__(self, input_size, output_size):
        self.weights = np.random.randn(input_size, output_size)
        self.bias = np.random.randn(output_size)

    def forward(self, inputs):
        output = np.dot(inputs, self.weights) + self.bias
        return output

# Example usage
input_data = np.array([[1, 2, 3], [4, 5, 6]])
dense_layer = DenseLayer(input_size=3, output_size=2)
output = dense_layer.forward(input_data)
print(output)


[[ -1.6964774   -5.39947716]
 [ -1.47146202 -14.41064285]]


In [ ]:
4. Write the Python code for a dense layer in plain Python (that is, with list comprehensions
and functionality built into Python).


In [4]:
import numpy as np

class DenseLayer:
    def __init__(self, input_size, output_size):
        self.weights = np.random.randn(input_size, output_size)
        self.bias = np.random.randn(output_size)

    def forward(self, inputs):
        output = [sum(weight * input_value for weight, input_value in zip(row, inputs)) + bias
                  for row, bias in zip(self.weights, self.bias)]
        return output

# Example usage
input_data = [1, 2, 3]
dense_layer = DenseLayer(input_size=3, output_size=2)
output = dense_layer.forward(input_data)
print(output)


[0.44595892527931114, 2.9727141380982665]


In [ ]:
5. What is the “hidden size” of a layer?


In [ ]:
The "hidden size" of a layer refers to the number of neurons or units in that layer. It represents the dimensionality or number of output values produced by that layer.



In [ ]:
6. What does the t method do in PyTorch?


In [ ]:
In PyTorch, the t method is used to transpose a tensor. It swaps the dimensions of the tensor, turning rows into columns and vice versa.

In [ ]:
7. Why is matrix multiplication written in plain Python very slow?


In [ ]:
Matrix multiplication written in plain Python is slow because it involves nested loops and individual element-wise multiplications, resulting in a high computational complexity. Python's built-in list comprehensions and lack of optimized matrix operations make it inefficient for large-scale matrix multiplication compared to libraries like NumPy or frameworks like PyTorch, which are implemented in lower-level languages and have highly optimized matrix multiplication algorithms.


In [ ]:
8. In matmul, why is ac==br?


In [ ]:
In matrix multiplication (matmul), the condition ac == br ensures that the inner dimensions of the two matrices being multiplied are the same. The matrices a and b should have dimensions (a_rows, a_cols) and (b_rows, b_cols), respectively, where a_cols must be equal to b_rows for the multiplication to be valid.


In [ ]:
9. In Jupyter Notebook, how do you measure the time taken for a single cell to execute?


In [ ]:
In Jupyter Notebook, we can measure the time taken for a single cell to execute using the %%timeit magic command. Simply prepend %%timeit at the beginning of the cell and run it. The command will automatically execute the cell multiple times and provide information about the average execution time.

In [ ]:
10. What is elementwise arithmetic?


In [ ]:
Elementwise arithmetic refers to performing arithmetic operations (addition, subtraction, multiplication, division, etc.) on corresponding elements of two or more tensors or matrices. Each element in one tensor is paired with the corresponding element in another tensor, and the operation is applied element-wise. This operation is possible when the tensors have compatible shapes or can be broadcasted to match each other's shape.

In [ ]:
11. Write the PyTorch code to test whether every element of a is greater than the
corresponding element of b.


In [5]:
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([0, 2, 2])

result = torch.all(a > b)
print(result)


tensor(False)


In [ ]:
12. What is a rank-0 tensor? How do you convert it to a plain Python data type?


In [6]:
import torch

scalar_tensor = torch.tensor([])

scalar = scalar_tensor.item()
print(scalar)


ValueError: only one element tensors can be converted to Python scalars

In [ ]:
13. How does elementwise arithmetic help us speed up matmul?


In [ ]:
Elementwise arithmetic helps speed up matrix multiplication by allowing parallelization and vectorization of computations. Rather than performing individual multiplications and additions in a loop, elementwise operations can be executed in parallel, leveraging optimized routines provided by libraries like NumPy or PyTorch. This enables more efficient utilization of hardware resources and takes advantage of hardware acceleration, resulting in significant speed improvements.

In [ ]:
14. What are the broadcasting rules?


In [ ]:
Broadcasting rules determine how two tensors with different shapes can be combined or operated upon element-wise. The rules define conditions under which two tensors can be broadcasted to have compatible shapes for elementwise operations. The broadcasting rules are as follows:

If the tensors have the same number of dimensions, but one or more dimensions differ in size, the tensor with size 1 in a particular dimension is broadcasted to match the size of the corresponding dimension in the other tensor.

If one of the tensors has fewer dimensions than the other, 1s are prepended to its shape to match the number of dimensions.

If the size of a dimension in one tensor is 1, and the size of the same dimension in the other tensor is greater than 1, the tensor with size 1 is broadcasted along that dimension.

In [ ]:
15. What is expand_as? Show an example of how it can be used to match the results of
broadcasting.

In [ ]:
The expand_as method in PyTorch is used to expand the size of a tensor to match the size of another tensor. It takes the shape of the target tensor as an argument and returns a new tensor with the expanded size. It can be used to match the results of broadcasting. Here's an example:

In [7]:
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([[1, 2, 3], [4, 5, 6]])

expanded_a = a.expand_as(b)
print(expanded_a)


tensor([[1, 2, 3],
        [1, 2, 3]])
